Prueba Step coverage 60%

diff --git a/.github/workflows/maven-jacoco.yml b/.github/workflows/maven-jacoco.yml
--- a/.github/workflows/maven-jacoco.yml
+++ b/.github/workflows/maven-jacoco.yml
@@ -48,10 +48,11 @@ jobs:
 
       - name: Check coverage percentage 60%
         run: |
-          COVERAGE=$("${ steps.jacoco.outputs.coverage }" | tr -d '%')
-          if [ $COVERAGE -lt 60 ]; then
-           echo "Code coverage is below 60%, setting workflow status to failure."
-           exit 1
+          COVERAGE=${steps.jacoco.outputs.coverage}
+          echo "coverage = $COVERAGE"
+          if [ $COVERAGE -lt 0.60 ]; then
+            echo "Code coverage is below 60%, setting workflow status to failure."
+            exit 1
           fi
 
       - name: Comment on PR with coverage percentages
